apiVersion: v1
kind: Service
metadata:
  name: jobs-service # Internal DNS name
  namespace: food-rescue-live
spec:
  type: ClusterIP
  selector:
    app: jobs-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082