apiVersion: v1
kind: Service
metadata:
  name: feedback-service # The internal DNS name
  namespace: food-rescue-live
spec:
  type: ClusterIP
  selector:
    app: feedback-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084