apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service # This MUST match the 'app' label in your Deployment
  ports:
    - protocol: TCP
      port: 8080       # The port inside the cluster
      targetPort: 8080 # The port on your container
      nodePort: 31080  # The port you will access from your Pi's IP